UPDATE projectC.user SET fullName = 'kjnev', firstName = null, username = null, lastName = null, password = null, email = 'eno', age = -1226225658, contact = null, country = null, city = null, cp = null, Test = null WHERE id = 47;
UPDATE projectC.user SET fullName = 'be', firstName = null, username = null, lastName = null, password = null, email = 'et', age = 1, contact = null, country = null, city = null, cp = null, Test = null WHERE id = 48;
UPDATE projectC.user SET fullName = 'eg', firstName = null, username = null, lastName = null, password = 'egrg', email = 'gre', age = 12, contact = 1, country = 'ef', city = 'eg', cp = 123, Test = null WHERE id = 49;
UPDATE projectC.user SET fullName = 'eg', firstName = 'eg', username = null, lastName = 'reg', password = 'getv', email = 'eg', age = 12, contact = 132, country = 'te', city = 'eg', cp = 143, Test = null WHERE id = 50;
UPDATE projectC.user SET fullName = 'ef', firstName = null, username = null, lastName = null, password = 'aze', email = 'fe', age = 11, contact = 11, country = 'srg', city = '	aae', cp = 121, Test = null WHERE id = 51;
UPDATE projectC.user SET fullName = 'de', firstName = null, username = null, lastName = null, password = 'de', email = 'de', age = 1, contact = 213, country = 'def', city = 'dz', cp = 123, Test = null WHERE id = 52;
UPDATE projectC.user SET fullName = 'aze', firstName = null, username = null, lastName = null, password = 'aa', email = 'aze', age = 12, contact = 11, country = 'aze', city = 'asd', cp = 123, Test = null WHERE id = 53;
UPDATE projectC.user SET fullName = 'magic', firstName = null, username = null, lastName = null, password = 'saz', email = '@agic@gmail.com', age = 12, contact = 123, country = 'azs', city = 'gt', cp = 12221, Test = null WHERE id = 54;
UPDATE projectC.user SET fullName = 'magic', firstName = null, username = null, lastName = null, password = 'az', email = '@agic6@gmail.com', age = 11, contact = 12, country = 'azsde', city = 'aq', cp = 111, Test = null WHERE id = 55;
UPDATE projectC.user SET fullName = 'aze', firstName = null, username = null, lastName = null, password = 'az', email = 'aze@ml.com', age = 12, contact = 12, country = 'aze', city = 'aze', cp = 123, Test = null WHERE id = 56;
UPDATE projectC.user SET fullName = 'aze', firstName = null, username = 'ae', lastName = null, password = 'az', email = 'eza@gmail.com', age = 12, contact = 132, country = 'ased', city = 'asz', cp = 21, Test = null WHERE id = 57;
UPDATE projectC.user SET fullName = 'az', firstName = 'az', username = 'az', lastName = 'az', password = 'az', email = 'az@az.com', age = 12, contact = 12, country = 'az', city = 'a', cp = 1, Test = null WHERE id = 58;
UPDATE projectC.user SET fullName = 'azsq', firstName = null, username = 'qsz', lastName = null, password = 'aq', email = 'qsz@muy.com', age = 11, contact = 123, country = 'asqsd', city = 'qsd', cp = 111, Test = null WHERE id = 59;
UPDATE projectC.user SET fullName = 'azer', firstName = null, username = 'azer', lastName = null, password = 'qs', email = 'azer@myges.com', age = 12, contact = 11, country = 'cnol', city = 'azq', cp = 1111, Test = null WHERE id = 60;
UPDATE projectC.user SET fullName = 'zaaa', firstName = null, username = 'aza', lastName = null, password = 'qs', email = 'aza@myg.com', age = 1, contact = 12, country = 'az', city = 'az', cp = 21, Test = null WHERE id = 61;
UPDATE projectC.user SET fullName = 'kat', firstName = null, username = 'kat', lastName = null, password = 'aw', email = 'kat', age = 1, contact = 1, country = 'za', city = 'az', cp = 11, Test = null WHERE id = 62;
UPDATE projectC.user SET fullName = 'as', firstName = null, username = 'azz', lastName = null, password = 'aq', email = 'as#', age = 1, contact = 1, country = 'a', city = '1', cp = 1, Test = null WHERE id = 63;
UPDATE projectC.user SET fullName = 'mm', firstName = null, username = 'mm', lastName = null, password = 'mm', email = 'mm@mm', age = 1, contact = 2, country = 'qs', city = 'wx', cp = 21, Test = null WHERE id = 68;
UPDATE projectC.user SET fullName = 'pk', firstName = null, username = 'pk', lastName = null, password = 'jk', email = 'pk@kk', age = 1, contact = 2, country = 'k', city = 'a', cp = 2, Test = null WHERE id = 69;
UPDATE projectC.user SET fullName = 'bh', firstName = null, username = 'bh', lastName = null, password = 'bh', email = 'bh@h', age = 1, contact = 1, country = 'j', city = 'd', cp = 1, Test = null WHERE id = 70;
UPDATE projectC.user SET fullName = 'fv', firstName = null, username = 'fv', lastName = null, password = 'fv', email = 'fv', age = 1, contact = 1, country = 'a', city = 'a', cp = 1, Test = null WHERE id = 71;
UPDATE projectC.user SET fullName = 'w', firstName = null, username = 'w', lastName = null, password = 'w', email = 'w', age = 1, contact = 0, country = 'w', city = 'w', cp = 1, Test = null WHERE id = 72;
UPDATE projectC.user SET fullName = 'azsd', firstName = null, username = '3', lastName = null, password = 'n', email = 'xs', age = -1823530672, contact = 0, country = 'n', city = 'n', cp = -1823571176, Test = null WHERE id = 73;
UPDATE projectC.user SET fullName = 'jb', firstName = null, username = 'jb', lastName = null, password = 'vc', email = 'jb@jj', age = 1, contact = 21, country = 'sz', city = 'qs', cp = 32, Test = null WHERE id = 74;
UPDATE projectC.user SET fullName = 'xx', firstName = null, username = 'xx', lastName = null, password = 'kk', email = 'xx@nxknc', age = 11, contact = 11, country = 'kkk', city = 'kk', cp = 11, Test = null WHERE id = 75;
UPDATE projectC.user SET fullName = 'd', firstName = null, username = 'd', lastName = null, password = 'd', email = 'd', age = -1212893016, contact = 0, country = 'dd', city = 'd', cp = 204186288, Test = null WHERE id = 76;
UPDATE projectC.user SET fullName = 'd', firstName = null, username = 'd', lastName = null, password = 'd', email = 'd', age = -1212893016, contact = 0, country = 'd', city = 'd', cp = 204186288, Test = null WHERE id = 77;
UPDATE projectC.user SET fullName = 'lucky', firstName = null, username = 'audesandrine6', lastName = null, password = 'test', email = 'audesandrine6@gmail.com', age = 3, contact = 6607899765, country = 'FRANCE', city = 'paris', cp = 9112, Test = null WHERE id = 78;
UPDATE projectC.user SET fullName = 'n', firstName = null, username = 'b', lastName = null, password = 'a', email = 'b', age = 1, contact = 1, country = 'w', city = 'a', cp = 2, Test = null WHERE id = 79;
UPDATE projectC.user SET fullName = 'm', firstName = null, username = 'm', lastName = null, password = 'm', email = 'm', age = -1312728920, contact = 0, country = 'm', city = 'm', cp = 476152496, Test = null WHERE id = 80;
UPDATE projectC.user SET fullName = 'm', firstName = 'o', username = 'm', lastName = null, password = 'm', email = 'm', age = 1, contact = 1, country = 'm', city = 'm', cp = 1, Test = null WHERE id = 81;
UPDATE projectC.user SET fullName = 'klm', firstName = null, username = 'klm', lastName = null, password = 'jk', email = 'klm@lm', age = 12, contact = 12, country = 'az', city = 'aq', cp = 12, Test = null WHERE id = 84;
UPDATE projectC.user SET fullName = 'qsd', firstName = null, username = 'aqm', lastName = null, password = 'vbb', email = 'aq@s', age = 1, contact = 23, country = 'qsd', city = 'wx', cp = 12, Test = null WHERE id = 85;
UPDATE projectC.user SET fullName = 'full', firstName = null, username = 'aude', lastName = null, password = 'bvj', email = 'aude@tes', age = 12, contact = 123, country = 'test', city = 'test', cp = 1233, Test = null WHERE id = 86;
UPDATE projectC.user SET fullName = 'test', firstName = null, username = 'test', lastName = null, password = 'test', email = 'test@email', age = 12, contact = 123, country = 'dff', city = 'ed', cp = 123, Test = null WHERE id = 87;
